sudo: false
language: node_js
node_js:
  - "node"
  - "iojs"
  - "6.0"
  - "5.0"
  - "4.2"
  - "0.12"
  - "0.10"
before_script:
  - sed -i 's/4.0.0-alpha.1/4.0.0/g' node_modules/gulp/package.json
after_script:
  - npm run coveralls
  - npm run lint
git:
  depth: 10
